### ISSUE TITLE
Voice Commands

### ISSUE THREAD

**Issue by oxhey** [neil-morrison44/lg-alexa-node#1]
What voice commands work with this appart from turning the tv off/on and opening an app.

Do any of the other methods from lgtv2 work such as setvolume or can they be added?

**Comment by neil-morrison44** [comment]
They don't work, but could be added.
Alexa treats everything like a light switch though, so you'd end up with some awkward phrasing like "Alexa, turn on volume up" and "Alexa, switch on tv pause" etc

**Comment by oxhey** [comment]
Okay Thanks.

**Comment by oxhey** [comment]
I have just tried running and get : 


/mnt/d/Desktop/lg-alexa-node-master/node_modules/fauxmojs/lib/index.js:11
  constructor(options = {}) {
                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/d/Desktop/lg-alexa-node-master/index.js:5:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
root@WebDev:/mnt/d/Desktop/lg-alexa-node-master#

**Comment by neil-morrison44** [comment]
What version of nodeJS are you running?
The default parameters stuff is fairly recently added to node, so it's probably that

**Comment by oxhey** [comment]
4.2.6

**Comment by neil-morrison44** [comment]
Yeah, this'll only work on node versions > 6.0.0

**Comment by oxhey** [comment]
working now. 👍     

Just a thought but, if Alexa treats it like a light why cant other commands be added. I have a wifi light and I can say "set brightness to X percent"

**Comment by neil-morrison44** [comment]
Looks like they've added a few more things to the skillset since I last looked at it:
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#entertainment-control-messages

I'm using https://github.com/dsandor/fauxmojs to pretend to be a switch.
I'll have another look at it at some point to see if I can handle the expanded smart home stuff somehow.
Hopefully someone'll put together a nice interface now that Siri, Alexa, and Google Home all support DIY devices.

**Comment by oxhey** [comment]
I look forward to the update :)
